# Generated by Django 4.1.7 on 2023-02-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(default='https://palchevsky.ru/images/blogpost.png', max_length=300),
        ),
    ]
