# Generated by Django 4.1.7 on 2023-02-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_category_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='myblog.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
