# Generated by Django 4.1.7 on 2023-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_category_delete_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
