# Generated by Django 4.1.7 on 2023-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
