# Generated by Django 4.1.7 on 2023-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_alter_category_divided'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
