# Generated by Django 4.1.7 on 2023-03-01 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_category_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 20, 5, 26, 240462)),
        ),
    ]
