# Generated by Django 4.1.7 on 2023-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_post_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_of_creation',
        ),
    ]
